[workspace]
members = [
  "anyrun",
  "anyrun-plugin",
  "anyrun-macros",
  "plugins/symbols",
  "plugins/kidex",
  "plugins/translate",
  "plugins/randr",
  "plugins/stdin",
  "plugins/dictionary",
  "plugins/nix-run",
  "plugins/window-switcher",
  "plugins/anyrun-applications",
  "plugins/anyrun-calc",
  "plugins/anyrun-findfiles",
  "plugins/anyrun-git-projects",
  "plugins/anyrun-shell-wrapper",
  "plugins/anyrun-shell-wrapper-once",
  "plugins/anyrun-universal-action",
  "plugins/anyrun-websearch",
  "plugins/anyrun-zoxide",
  "plugins/anyrun-kde-setting",
  "anyrun-helper",
  "plugins/anyrun-browser",
  "plugins/anyrun-sync-manager",
  "plugins/kde-clipboard",
  "plugins/kill-port",
  "anyrun-provider",
  "anyrun-provider/anyrun-provider-ipc",
  "plugins/anyrun-bluetooth",
  "tests/mock-plugins/basic",
  "tests/mock-plugins/panic-init",
  "tests/mock-plugins/hang-query",
  # "plugins/plugin-sample",
]
resolver = "2"

[workspace.dependencies]
anyrun-helper    = { path = "./anyrun-helper" }
anyrun-interface = { git = "https://github.com/anyrun-org/anyrun-interface" }

[profile.release]
codegen-units = 16
debug         = false
incremental   = false
lto           = "thin"
opt-level     = 2
panic         = "abort"
strip         = true

# Fast compile profile for development iteration
[profile.dev-fast]
inherits  = "dev"
opt-level = 1
